### ISSUE TITLE
OGP画像を生成する

### ISSUE THREAD

**Issue by r4ai** [ricora/alg.tus-ricora.com#1]

**Comment by 3w36zj6** [comment]
## 背景画像

![image](https://user-images.githubusercontent.com/52315048/293037802-59dc601d-4d17-4071-81f5-30dbddd08664.png)

## フォント

https://github.com/ookamiinc/kinto

## 生成例

![image](https://user-images.githubusercontent.com/52315048/293038598-93cc0c6a-2102-42bf-a6ff-f593278cb725.png)
