### ISSUE TITLE
目次を実装する

### ISSUE THREAD

**Issue by 3w36zj6** [ricora/alg.tus-ricora.com#73]

**Comment by r4ai** [comment]
- headingsの取得方法：https://docs.astro.build/en/guides/markdown-content/#exported-properties
- [IntersectionObserver](https://developer.mozilla.org/ja/docs/Web/API/IntersectionObserver)で、現在の目次のheadingをハイライトすると良さそう
- 参考デザイン：https://vitepress.dev/guide/routing
